### ISSUE TITLE
Can't signup with email address containing uppercase letters

### ISSUE THREAD

**Issue by GirkovArpa** [ordermsg/client-electron#7]
**Describe the bug**
Trying to signup with an email address containing uppercase letters results in an error message stating invalid email.

**To Reproduce**
Try to sign up with the email address `GirkovArpa@protonmail.com`.  It gets rejected.  But `girkovarpa@protonmail.com` is accepted.

**Expected behavior**
It should not reject the email for being invalid.

**Your setup:**
 - OS: Windows
 - Client version: Latest

**Comment by portasynthinca3** [comment]
Hey! Thanks for showing interest in the project. Sure, I can fix this particular issue, though please be advised that the project is undergoing heavy redevelopment at the moment on both ends. It's probably best not to use it at all until I'm done.

The only things you can do at the moment are signing up, logging in and changing your profile details, even though the sea of buttons suggest otherwise.

Again, thank you for your interest in the project. Come back later if you fell like so!

**Comment by portasynthinca3** [comment]
Fixed
